{% set name = "sklearn-genetic" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sklearn-genetic-{{ version }}.tar.gz
  sha256: 864981a46afccc7bc3d5677d68282c05cc128b16b93082494960e9ea3bad6f20

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - deap >=1.0.2
    - multiprocess
    - numpy
    - python >=3.6
    - scikit-learn >=0.23

test:
  imports:
    - genetic_selection

about:
  home: https://github.com/manuel-calzolari/sklearn-genetic
  summary: Genetic feature selection module for scikit-learn
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - manuel-calzolari
