{% set name = "sklearn-genetic" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sklearn-genetic-{{ version }}.tar.gz
  sha256: d5b5623e59feb6722cf5bb03b914dc93b8d93b3dff9103e5b9825241281b5338

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - deap >=1.0.2
    - multiprocess
    - numpy
    - python >=3.7
    - scikit-learn >=1.0

test:
  imports:
    - genetic_selection

about:
  home: https://github.com/manuel-calzolari/sklearn-genetic
  summary: Genetic feature selection module for scikit-learn
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - manuel-calzolari
