{% set name = "sklearn-genetic" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sklearn-genetic-{{ version }}.tar.gz
  sha256: 81b44319498656ca50e14fc300cccf2f1434a35ddaf950b86c7d16e03fe0d8d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - deap >=1.0.2
    - python >=2.7
    - scikit-learn >=0.20.3

test:
  imports:
    - genetic_selection

about:
  home: https://github.com/manuel-calzolari/sklearn-genetic
  summary: Genetic feature selection module for scikit-learn
  license: LGPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - manuel-calzolari
